<#
    Copies built artefacts into the live game Data folder.

    DEPLOY CADENCE - this drives the whole iteration loop:

      .prompt files        top-level ones hot-reload ("Reload prompts" in the UI)
      submodule .prompt    FULL GAME RESTART. Measured: 0340_kinship.prompt was
                           deployed at 10:34 and a conversation at 11:18, after
                           a "Reload prompts", still rendered the OLD text -
                           confirmed by grepping the rendered request in
                           logs/openrouter_input.log for a phrase unique to the
                           new version. Either the reload skips submodules/ or
                           the composed character bio is cached per actor.
                           ALWAYS verify a prompt edit by grepping the input log
                           for new wording before judging whether it worked; a
                           stale render looks exactly like an instruction the
                           model ignored, and one round of prompt tuning was
                           spent on that mistake.
      trigger/action YAML  reload from disk in the SkyrimNet UI, no restart
      .pex scripts         FULL GAME RESTART - a save reload reuses cached
                           scripts and will run the OLD code while showing you
                           the new file on disk
      SKSE panel DLL       FULL GAME RESTART - loaded once at startup. A stale
                           one loads happily and simply lacks the new UI, which
                           looks like a change that did not work rather than one
                           that was never installed

    DO NOT run this while Skyrim is running if -Scripts is included: the game
    holds .pex open and a half-written script is worse than a stale one. The
    guard below refuses rather than trusting you to remember.

    Usage:
        powershell -ExecutionPolicy Bypass -File "tools\deploy.ps1"
        powershell -ExecutionPolicy Bypass -File "tools\deploy.ps1" -PromptsOnly
#>
[CmdletBinding()]
param(
    [string]$SkyrimRoot = '',
    [switch]$PromptsOnly,
    # Must match package.ps1's default, or a local test exercises a different
    # folder name from the one the archive ships.
    [string]$PluginId = 'deadohiosky48.kinship'
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '_common.ps1')
$SkyrimRoot = Resolve-SkyrimRootOrThrow -Override $SkyrimRoot
$repo = Split-Path -Parent $PSScriptRoot
$data = Join-Path $SkyrimRoot 'Data'
if (-not (Test-Path $data)) { throw "Not found: $data" }

$running = Get-Process -Name 'SkyrimSE' -ErrorAction SilentlyContinue
if ($running -and -not $PromptsOnly) {
    throw "Skyrim is running. Close it before deploying scripts, or pass -PromptsOnly (prompts hot-reload safely)."
}

function Copy-Tree($from, $to, $label) {
    if (-not (Test-Path $from)) { Write-Host "  skip  $label (nothing at $from)"; return }
    New-Item -ItemType Directory -Force -Path $to | Out-Null
    Copy-Item -Path (Join-Path $from '*') -Destination $to -Recurse -Force
    Write-Host "  ok    $label"
}

Write-Host "Deploying to $data`n"

# SETTINGS ARE LIVE STATE, NOT SHIPPED CONTENT.
#
# The copy below is a blanket recursive -Force, which happily overwrites
# settings.yaml with the repo's shipped defaults - silently reverting whatever
# is actually configured. That is not hypothetical: a deploy turned life stages
# and scaling back OFF mid-playthrough moments after they had been switched on,
# and nothing in the output said so.
#
# But settings.yaml cannot simply be skipped either: a config key must exist in
# BOTH manifest.yaml and settings.yaml to be readable at all, so a stale file
# would make every newly added key silently return its Papyrus default forever.
#
# So: capture the live values first, copy (picking up new keys and updated
# comments), then put the captured values back. New keys arrive at their shipped
# default; existing ones keep whatever the player chose.
$settingsRel = Join-Path 'SKSE\Plugins\SkyrimNet\config\plugins\SkyrimNet Kinship' 'settings.yaml'
$liveSettings = Join-Path $data $settingsRel
$utf8 = New-Object System.Text.UTF8Encoding $false
$keep = @{}
if (Test-Path $liveSettings) {
    foreach ($line in [System.IO.File]::ReadAllLines($liveSettings, [System.Text.Encoding]::UTF8)) {
        if ($line -match '^\s*(kin[A-Za-z0-9_]+)\s*:\s*(.+?)\s*$') { $keep[$Matches[1]] = $Matches[2] }
    }
}

# Prompts, manifest and settings - all hot-reloadable.
Copy-Tree (Join-Path $repo 'SKSE') (Join-Path $data 'SKSE') 'SKSE tree (prompt, manifest, settings)'

# THE BETA 25 COPY TOO, or local testing only ever exercises one of the two
# layouts the archive ships - and it would be whichever one this machine's
# SkyrimNet happens to read. The archive's copy is GENERATED by package.ps1;
# this mirrors it so a prompt edit reaches the running game on either build.
# Same file, two places, one source: the repo tree above.
$snLive  = Join-Path $data 'SKSE\Plugins\SkyrimNet'
$extLive = Join-Path $snLive "external\$PluginId"
$srcPrompts = Join-Path $repo 'SKSE\Plugins\SkyrimNet\prompts'
if (Test-Path $srcPrompts) {
    New-Item -ItemType Directory -Force -Path $extLive | Out-Null
    Copy-Item $srcPrompts $extLive -Recurse -Force
    # A manifest has to exist or Beta 25 ignores the folder, and the id must
    # equal the folder name. Version is irrelevant for a local deploy - the
    # release build writes the real one - but it has to be valid semver.
    $devManifest = [ordered]@{
        id                    = $PluginId
        type                  = 'bundle'
        title                 = 'SkyrimNet Kinship'
        tagline               = 'Children know who their parents are, and mothers never forget.'
        description           = 'Local development build.'
        author                = ($PluginId -split '\.')[0]
        nsfw                  = $false
        icon                  = 'sparkles'
        version               = '0.0.1'
        min_skyrimnet_version = '0.25.0'
    }
    [System.IO.File]::WriteAllText(
        (Join-Path $extLive 'manifest.json'),
        ($devManifest | ConvertTo-Json -Depth 5),
        (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "  also      external\$PluginId (Beta 25 layout)"
}

if ($keep.Count -gt 0 -and (Test-Path $liveSettings)) {
    $restored = 0
    $out = foreach ($line in [System.IO.File]::ReadAllLines($liveSettings, [System.Text.Encoding]::UTF8)) {
        if ($line -match '^\s*(kin[A-Za-z0-9_]+)\s*:\s*(.+?)\s*$' -and $keep.ContainsKey($Matches[1])) {
            $key = $Matches[1]
            if ($Matches[2] -ne $keep[$key]) { $restored++ }
            "${key}: $($keep[$key])"
        } else { $line }
    }
    [System.IO.File]::WriteAllLines($liveSettings, $out, $utf8)
    if ($restored -gt 0) {
        Write-Host "  ok    kept $restored live setting(s) that differ from the shipped defaults" -ForegroundColor Cyan
    } else {
        Write-Host "  ok    live settings preserved"
    }
}

if (-not $PromptsOnly) {
    Copy-Tree (Join-Path $repo 'Scripts') (Join-Path $data 'Scripts') 'compiled scripts'

    # THE PANEL DLL, which this script did not copy for the whole of its life.
    #
    # package.ps1 takes the DLL straight from build\Release, so a RELEASE always
    # carried the current panel - but deploying never did. Every panel change
    # had to be hand-copied, and the failure is silent in the worst way: the
    # game loads a stale DLL perfectly happily and the new UI is simply absent,
    # which reads as "the change did not work" rather than "the change was not
    # installed". A tooltip built and verified in one session was still missing
    # in-game a day later for exactly this reason.
    #
    # Absent is normal and not an error: the DLL is optional, and a Papyrus-only
    # working copy has never built one.
    $dll = Join-Path $repo 'SKSE_Source\build\Release\SkyrimNetKinship.dll'
    if (Test-Path $dll) {
        $dllDest = Join-Path $data 'SKSE\Plugins\SkyrimNetKinship.dll'
        # IN PLACE, DELIBERATELY. The live file is a Vortex HARDLINK into the
        # staging folder; Copy-Item -Force overwrites the contents and keeps the
        # link, where Remove-Item then copy would break it and leave Vortex
        # believing it still manages a file it no longer shares.
        New-Item -ItemType Directory -Force -Path (Split-Path -Parent $dllDest) | Out-Null
        Copy-Item $dll $dllDest -Force
        $kb = [math]::Round((Get-Item $dllDest).Length / 1KB)
        if ((Get-FileHash $dll).Hash -eq (Get-FileHash $dllDest).Hash) {
            Write-Host "  ok    SKSE panel DLL ($kb KB)"
        } else {
            # Only reachable if something else holds the file. Worth saying
            # loudly rather than reporting a copy that did not land.
            Write-Host "  FAIL  SKSE panel DLL did not land - is the file locked?" -ForegroundColor Red
        }
    } else {
        Write-Host "  skip  SKSE panel DLL (not built - run tools\build-dll.ps1)"
    }

    Write-Host "`n  NOTE: scripts changed - a FULL GAME RESTART is required." -ForegroundColor Yellow
    Write-Host "        Reloading a save reuses cached scripts and runs the old code." -ForegroundColor Yellow
}

Write-Host "`nDone." -ForegroundColor Green
